apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-master-config
  namespace: prod
data:
  my.cnf: |
    [client]
    default-character-set = utf8mb4

    [mysql]
    default-character-set = utf8mb4

    [mysqld]
    character-set-client-handshake = FALSE
    character-set-server = utf8mb4
    collation-server = utf8mb4_unicode_ci
    server-id = 1
    log_bin = mysql-bin

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: batch-fluent-bit-config
  namespace: prod
data:
  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Log_Level debug
        Parsers_File parsers.conf

    [INPUT]
        Name tail
        Path /app/logs/myapp-*.log
        Read_from_Head false

    [OUTPUT]
        name slack
        match *
        webhook https://hooks.slack.com/services/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