apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-deployment
  namespace: prod
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: batch
  template:
    metadata:
      labels:
        app: batch
    spec:
      containers:
        - name: spring-batch-container
          image: 192.168.0.212:5555/spring-batch:20240818-012009
          ports:
            - containerPort: 8096
          volumeMounts:
            - name: batch-logs
              mountPath: /app/logs
          env:
            - name: DATABASE_HOST
              value: "batch-mysql-master-service"
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_USER
              value: root
            - name: DATABASE_PASSWORD
              value: testtest

        - name: mysql-master-container
          image: 192.168.0.212:5555/mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: testtest
            - name: MYSQL_DATABASE
              value: main
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "no"
            - name: MYSQL_ROOT_HOST
              value: "%"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: batch-mysql-master-data
              mountPath: /var/lib/mysql
            - name: mysql-config-volume
              mountPath: /etc/mysql/my.cnf
              subPath: my.cnf

        - name: phpmyadmin-container
          image: 192.168.0.212:5555/phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: "batch-mysql-master-service"
            - name: PMA_PORT
              value: "3306"
            - name: PMA_USER
              value: root
            - name: PMA_PASSWORD
              value: testtest

        - name: fluent-bit
          image: 192.168.0.212:5555/fluent/fluent-bit
          volumeMounts:
            - name: batch-fluent-config
              mountPath: /fluent-bit/etc/fluent-bit.conf
              subPath: fluent-bit.conf
            - name: batch-logs
              mountPath: /app/logs

      volumes:
        - name: batch-logs
          persistentVolumeClaim:
            claimName: batch-logs-pvc
        - name: batch-mysql-master-data
          persistentVolumeClaim:
            claimName: batch-mysql-master-data-pvc
        - name: batch-fluent-config
          configMap:
            name: batch-fluent-bit-config
        - name: mysql-config-volume
          configMap:
            name: mysql-master-config